server:
  port: 8000

#spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 100
#        max-wait: 1000
#        min-idle: 10
#    password:

# logger 配置
logging:
  config: classpath:logback-spring.xml